-- MySQL Script generated by MySQL Workbench
-- 05/03/15 12:11:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema KoonolPax
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KoonolPax
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KoonolPax` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `KoonolPax` ;

-- -----------------------------------------------------
-- Table `KoonolPax`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`usuario` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`usuario` (
  `cod_u` INT(6) NOT NULL,
  `nick_u` VARCHAR(80) NOT NULL,
  `pass_u` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`cod_u`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`sello`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`sello` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`sello` (
  `cod_s` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `desc_s` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`cod_s`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`categoria` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`categoria` (
  `cod_cat` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `desc_cat` VARCHAR(80) NULL,
  PRIMARY KEY (`cod_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`interprete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`interprete` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`interprete` (
  `cod_i` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_i` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`cod_i`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`pedido_m`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`pedido_m` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`pedido_m` (
  `cod_p` INT(11) NOT NULL AUTO_INCREMENT,
  `fec_p` DATE NOT NULL,
  `fin_p` VARCHAR(1) NOT NULL,
  `cod_u` INT(6) NOT NULL,
  PRIMARY KEY (`cod_p`),
  INDEX `fk_pedidos_m_usuario1_idx` (`cod_u` ASC),
  CONSTRAINT `fk_pedidos_m_usuario1`
    FOREIGN KEY (`cod_u`)
    REFERENCES `KoonolPax`.`usuario` (`cod_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`disco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`disco` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`disco` (
  `cod_d` INT(6) NOT NULL AUTO_INCREMENT,
  `nom_d` VARCHAR(80) NOT NULL,
  `cod_i` INT(11) NOT NULL,
  `cant_d` INT(11) NOT NULL,
  `cod_s` SMALLINT(3) NOT NULL,
  `precio_d` FLOAT NOT NULL,
  `fec_d` DATE NOT NULL,
  `cod_cat` SMALLINT(3) NOT NULL,
  PRIMARY KEY (`cod_d`),
  INDEX `fk_disco_interprete1_idx` (`cod_i` ASC),
  INDEX `fk_disco_sello1_idx` (`cod_s` ASC),
  INDEX `fk_disco_categoria1_idx` (`cod_cat` ASC),
  CONSTRAINT `fk_disco_interprete`
    FOREIGN KEY (`cod_i`)
    REFERENCES `KoonolPax`.`interprete` (`cod_i`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disco_sello`
    FOREIGN KEY (`cod_s`)
    REFERENCES `KoonolPax`.`sello` (`cod_s`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disco_categoria`
    FOREIGN KEY (`cod_cat`)
    REFERENCES `KoonolPax`.`categoria` (`cod_cat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `KoonolPax`.`pedido_d`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KoonolPax`.`pedido_d` ;

CREATE TABLE IF NOT EXISTS `KoonolPax`.`pedido_d` (
  `cod_p` INT(11) NOT NULL,
  `cod_d` INT(6) NOT NULL,
  `cant_d` SMALLINT(3) NOT NULL,
  INDEX `fk_table1_pedidos_m1_idx` (`cod_p` ASC),
  INDEX `fk_pedido_d_disco1_idx` (`cod_d` ASC),
  CONSTRAINT `fk_pedidos_m`
    FOREIGN KEY (`cod_p`)
    REFERENCES `KoonolPax`.`pedido_m` (`cod_p`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_disco`
    FOREIGN KEY (`cod_d`)
    REFERENCES `KoonolPax`.`disco` (`cod_d`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
